#!/bin/bash
echo "post"
set -euo pipefail
#
jupyter serverextension enable --py nbserverproxy --sys-prefix
# labextensions
jupyter labextension install dask-labextension \
                             @jupyter-widgets/jupyterlab-manager \
                             @pyviz/jupyterlab_pyviz \
                             jupyter-leaflet

mkdir data2
#jupyter serverextension enable --py nbserverproxy --sys-prefix
#jupyter labextension install @jupyter-widgets/jupyterlab-manager@0.38 \
#                             @jupyterlab/hub-extension@0.12 \
#                             @pyviz/jupyterlab_pyviz@0.6.4 \
#                             jupyter-leaflet@0.8.1 \
#                             dask-labextension@0.3.0