#!/bin/bash
echo "post"
set -euo pipefail
#
jupyter serverextension enable --py nbserverproxy --sys-prefix
# labextensions
jupyter labextension install @jupyter-widgets/jupyterlab-manager \
                             @pyviz/jupyterlab_pyviz \
                             jupyter-leaflet

# download data
cd /home/jovyan
mkdir data
cd data
mkdir cp2
cd cp2
wget http://mcs.anl.gov/~scollis/cp2.tgz
tar -xvzf cp2.tgz
rm cp2.tgz
cd ..
wget http://mcs.anl.gov/~scollis/20171230.zip
unzip 20171230.zip
rm 20171230.zip
cd 20171230
cd ..
mkdir arm
cd arm
wget http://www.mcs.anl.gov/~scollis/pyart/csapr_test_case.nc
wget http://www.mcs.anl.gov/~scollis/pyart/nsaxsaprppiC1.a1.20140201.184802.nc
wget http://www.mcs.anl.gov/~scollis/pyart/sgpxsaprcmacsurI5.c1.20170801.044013.nc
cd ..
wget http://www.mcs.anl.gov/~scollis/one_we_prepared_earlier.nc
wget http://www.mcs.anl.gov/~scollis/era5_data.nc
cd /home/jovyan

#jupyter serverextension enable --py nbserverproxy --sys-prefix
#jupyter labextension install @jupyter-widgets/jupyterlab-manager@0.38 \
#                             @jupyterlab/hub-extension@0.12 \
#                             @pyviz/jupyterlab_pyviz@0.6.4 \
#                             jupyter-leaflet@0.8.1 \
#                             dask-labextension@0.3.0